export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const INCOME_TYPES_FETCHED = 'INCOME_TYPES_FETCHED';
export const CLEAR_INCOME_TYPES = 'CLEAR_INCOME_TYPES';
export const INCOME_FETCHED = 'INCOME_FETCHED';